spring:
  application:
    name: ai-zcode
  # session 配置
  session:
#    store-type: redis  不必指定，现在改为了自动检测（优先级：redis->JDBC->Map-based）
    # session 30 天过期
    timeout: 2592000
  profiles:
    active: local
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_zcode?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    # redis
  data:
    redis:
      host: localhost
      database: 0
      port: 6379
      password:
      ttl: 3600
server:
  port: 8234
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.aizcode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

