spring:
  application:
    name: ai-zcode
  # session 配置
  session:
#    store-type: redis  不必指定，现在改为了自动检测（优先级：redis->JDBC->Map-based）
    # session 30 天过期
    timeout: 2592000
  profiles:
    active: local
  #PgSQL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ai_zcode
    username: postgres
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

    # redis
  data:
    redis:
      host: localhost
      database: 0
      port: 6379
      password:
      ttl: 3600
server:
  port: 8234
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.aizcode.controller
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

